"""initial_schema

Revision ID: 77b6ea67e403
Revises: 
Create Date: 2026-06-29 13:51:08.077643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b6ea67e403'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False, comment="Nom de l'organisation"),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Identifiant URL-friendly (ex: acme-corp)'),
    sa.Column('plan', sa.Enum('FREE', 'STARTER', 'PRO', 'ENTERPRISE', name='plantype'), nullable=False, comment="Plan d'abonnement actuel"),
    sa.Column('max_agents', sa.Integer(), nullable=False, comment="Nombre maximum d'agents autorisés"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Organisation active ou suspendue'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique universel'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('agents',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nom lisible (ex: prod-server-01, db-master)'),
    sa.Column('hostname', sa.String(length=255), nullable=True, comment="Hostname détecté automatiquement par l'agent"),
    sa.Column('api_key', sa.String(length=64), nullable=False, comment="Clé secrète utilisée par l'agent pour s'authentifier"),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'PENDING', 'DISABLED', name='agentstatus'), nullable=False, comment='Statut de connexion actuel'),
    sa.Column('os_info', sa.String(length=255), nullable=True, comment='OS détecté (ex: Ubuntu 22.04 LTS)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment="Dernière adresse IP connue de l'agent"),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True, comment="Dernière fois que l'agent a envoyé des métriques"),
    sa.Column('description', sa.Text(), nullable=True, comment='Description libre (rôle du serveur, notes)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Agent actif (compte dans les limites du plan)'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique universel'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification (UTC)'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_api_key'), 'agents', ['api_key'], unique=True)
    op.create_index(op.f('ix_agents_organization_id'), 'agents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email unique, utilisé pour la connexion'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Hash bcrypt du mot de passe — JAMAIS le mot de passe clair'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="Nom complet affiché dans l'interface"),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Numéro pour alertes SMS (format international: +228...)'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='userrole'), nullable=False, comment="Rôle dans l'organisation"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Compte actif ou désactivé'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email vérifié via le lien de confirmation'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organisation à laquelle appartient cet utilisateur'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique universel'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification (UTC)'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('alerts',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Titre court (ex: CPU critique sur prod-server-01)'),
    sa.Column('message', sa.Text(), nullable=True, comment="Description détaillée de l'alerte"),
    sa.Column('metric', sa.Enum('CPU_USAGE', 'MEMORY_USAGE', 'DISK_USAGE', 'AGENT_DOWN', 'NETWORK_LATENCY', name='alertmetric'), nullable=False, comment="Quelle métrique a déclenché l'alerte"),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity'), nullable=False, comment='Niveau de gravité'),
    sa.Column('status', sa.Enum('FIRING', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False, comment="Statut actuel de l'alerte"),
    sa.Column('threshold_value', sa.Float(), nullable=True, comment="Seuil configuré qui a déclenché l'alerte (ex: 80.0 pour 80%)"),
    sa.Column('current_value', sa.Float(), nullable=True, comment='Valeur mesurée au moment du déclenchement (ex: 94.5)'),
    sa.Column('fired_at', sa.DateTime(), nullable=True, comment='Moment exact du déclenchement'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='Moment de la résolution (null si encore active)'),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True, comment="Moment de l'acquittement"),
    sa.Column('sms_sent', sa.Boolean(), nullable=True, comment='SMS envoyé ?'),
    sa.Column('email_sent', sa.Boolean(), nullable=True, comment='Email envoyé ?'),
    sa.Column('whatsapp_sent', sa.Boolean(), nullable=True, comment='WhatsApp envoyé ?'),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True, comment="User qui a acquitté l'alerte"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identifiant unique universel'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Date de création (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Date de dernière modification (UTC)'),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_agent_id'), 'alerts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_agent_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_organization_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_api_key'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
