"""add_trial_ends_at_to_organizations

Revision ID: a065ec5aea1e
Revises: eced1bb69736
Create Date: 2026-07-10 05:40:03.838462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a065ec5aea1e'
down_revision: Union[str, None] = 'eced1bb69736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('trial_ends_at', sa.DateTime(), nullable=True, comment='Date de fin de la periode d essai gratuit (null = pas de trial)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'trial_ends_at')
    # ### end Alembic commands ###
